[package]
name = "autoencoder"
version = "0.1.0"
edition = "2021"
description= "A simple autoencoder"

[dependencies]
burn = { workspace = true, features = ["wgpu", "dataset"] }
serde = {workspace = true}
serde_bytes = "0.11.15"
